FROM node:18-alpine

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm install

COPY . .

RUN npm run build

RUN mkdir -p ./src/public/avatars ./src/public/images && chmod -R 777 ./src/public

EXPOSE 3000

CMD ["node", "dist/app.js"]
